export const bg_PHB = ['Acolyte', 'Charlatan', 'Criminal', 'Custom Background', 'Entertainer', 'Folk Hero', 'Guild Artisan', 'Hermit', 'Noble', 'Outlander', 'Sage', 'Sailor', 'Soldier', 'Urchin', 'Variant Criminal (Spy)', 'Variant Entertainer (Gladiator)', 'Variant Guild Artisan (Guild Merchant)', 'Variant Noble (Knight)', 'Variant Noble (Retainers)', 'Variant Sailor (Pirate)'];
export const bg_XPHB = ['Acolyte', 'Artisan', 'Charlatan', 'Criminal', 'Entertainer', 'Farmer', 'Guard', 'Guide', 'Hermit', 'Merchant', 'Noble', 'Sage', 'Sailor', 'Scribe', 'Soldier', 'Wayfarer'];
export const bg_ToA = ['Anthropologist', 'Archaeologist'];
export const bg_TDCSR = ['Ashari', 'Clasp Member', 'Lyceum Scholar', 'Reformed Cultist', 'Variant Clasp Member (Myriad Operative)', 'Variant Whitestone Rifle Corps (Grey Hunter)', 'Whitestone Rifle Corps'];
export const bg_AAG = ['Astral Drifter', 'Wildspacer'];
export const bg_MOT = ['Athlete'];
export const bg_EGW = ['Augen Trust (Spy)', 'Cobalt Scholar (Sage)', 'Grinner', 'Luxonborn (Acolyte)', 'Myriad Operative (Criminal)', 'Revelry Pirate (Sailor)', 'Volstrucker Agent'];
export const bg_GGR = ['Azorius Functionary', 'Boros Legionnaire', 'Dimir Operative', 'Golgari Agent', 'Gruul Anarch', 'Izzet Engineer', 'Orzhov Representative', 'Rakdos Cultist', 'Selesnya Initiate', 'Simic Scientist'];
export const bg_BGDIA = ["Baldur's Gate Acolyte", "Baldur's Gate Charlatan", "Baldur's Gate Criminal", "Baldur's Gate Entertainer", "Baldur's Gate Folk Hero", "Baldur's Gate Guild Artisan", "Baldur's Gate Hermit", "Baldur's Gate Noble", "Baldur's Gate Outlander", "Baldur's Gate Sage", "Baldur's Gate Sailor", "Baldur's Gate Soldier", "Baldur's Gate Urchin", 'Faceless'];
export const bg_HWCS = ['Bandit Defector', 'Grounded', 'Wind-Touched'];
export const bg_ALCurseOfStrahd = ['Black Fist Double Agent', 'Dragon Casualty', 'Iron Route Bandit', 'Phlan Insurgent', 'Stojanow Prisoner', 'Ticklebelly Nomad'];
export const bg_ALElementalEvil = ['Caravan Specialist', 'Earthspur Miner', 'Harborfolk', 'Mulmaster Aristocrat', 'Phlan Refugee'];
export const bg_AI = ["Celebrity Adventurer's Scion", 'Failed Merchant', 'Gambler', 'Plaintiff', 'Rival Intern'];
export const bg_SCAG = ['City Watch', 'Clan Crafter', 'Cloistered Scholar', 'Courtier', 'Faction Agent', 'Far Traveler', 'Inheritor', 'Knight of the Order', 'Mercenary Veteran', 'Urban Bounty Hunter', 'Uthgardt Tribe Member', 'Variant City Watch (Investigator)', 'Waterdhavian Noble'];
export const bg_DoDk = ['Continental Nobility', 'Devoted Missionary', 'Mageborn', 'Survivor', 'Treasure Seeker', 'Variant Continental Nobility (Last of the Line)', 'Variant Devoted Missionary (Stargazer)', 'Variant Mageborn (Malfeasant Mage)', 'Variant Survivor (Veteran of the Civil War)', 'Variant Treasure Seeker (Soldier of Fortune)'];
export const bg_ALRageOfDemons = ['Cormanthor Refugee', 'Gate Urchin', 'Hillsfar Merchant', 'Hillsfar Smuggler', 'Secret Identity', 'Shade Fanatic', 'Trade Sheriff'];
export const bg_WBtW = ['Feylost', 'Witchlight Hand'];
export const bg_GoS = ['Fisher', 'Marine', 'Shipwright', 'Smuggler'];
export const bg_SatO = ['Gate Warden', 'Planar Philosopher'];
export const bg_BGG = ['Giant Foundling', 'Rune Carver'];
export const bg_VRGR = ['Haunted One', 'Investigator'];
export const bg_ERLW = ['House Agent'];
export const bg_PSA = ['Initiate', 'Initiate (Dissenter)', 'Vizier', 'Vizier (Dissenter)'];
export const bg_PSI = ['Inquisitor'];
export const bg_DSotDQ = ['Knight of Solamnia', 'Mage of High Sorcery'];
export const bg_SCC = ['Lorehold Student', 'Prismari Student', 'Quandrix Student', 'Silverquill Student', 'Witherbloom Student'];
export const bg_BMT = ['Rewarded', 'Ruined'];

export const backgroundSources = ["PHB", "XPHB", "ToA", "TDCSR", "AAG", "MOT", "EGW", "GGR", "BGDIA", "HWCS", "ALCurseOfStrahd", "ALElementalEvil", "AI", "SCAG", "DoDk", "ALRageOfDemons", "WBtW", "GoS", "SatO", "BGG", "VRGR", "ERLW", "PSA", "PSI", "DSotDQ", "SCC", "BMT"]